[package]
name = "ray_marching"
version = "0.1.0"
authors = ["Anton1320 <56134229+Anton1320@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
piston_window = "*"
image = "0.21.1"